### ISSUE TITLE
Does not initialize properly.

### ISSUE THREAD

**Issue by nebosphere19** [notify-events/homebridge#1]
Seem to have issue initializing this plugin...

[5/23/2022, 2:04:35 PM] [NotifyEvents] Initializing NotifyEvents platform...
[5/23/2022, 2:04:35 PM] [NotifyEvents] platform.action.host: Invalid host

Any ideas? Here's my config (token redacted for privacy):

{
    "platform": "NotifyEvents",
    "action": {
        "enabled": false,
        "listen": "0.0.0.0",
        "port": 53535,
        "host": "",
        "path": "/"
    },
    "channels": [
        {
            "title": "SMS",
            "token": "XXXXXXXXXXXXXXXXXXX",
            "messages": [
                {
                    "name": "Fridge Door Notifier",
                    "title": "ALERT: A Fridge Door is Open!!!!",
                    "text": "Please close it. ",
                    "priority": "highest",
                    "level": "warning",
                    "actions": []
                }
            ]
        }
    ]

**Comment by papajojo** [comment]
Hello, @nebosphere19. 
Please update plugin version up to 1.2.1, there was actually a bug with host validation. 

Thanks for the report!

**Comment by nebosphere19** [comment]
Thanks! Did that and now it crashes home bridge when it runs:

[5/24/2022, 10:40:11 AM] [NotifyEvents] Initializing NotifyEvents platform...
[5/24/2022, 10:40:11 AM] TypeError: Cannot read properties of undefined (reading 'enabled')
    at Object.validate (/usr/local/lib/node_modules/homebridge-notifyevents/homebridge-ui/public/js/common.js:60:48)
    at validate (/usr/local/lib/node_modules/homebridge-notifyevents/homebridge-ui/public/js/common.js:455:28)
    at validate (/usr/local/lib/node_modules/homebridge-notifyevents/homebridge-ui/public/js/common.js:425:37)
    at Object.validate (/usr/local/lib/node_modules/homebridge-notifyevents/homebridge-ui/public/js/common.js:425:37)
    at new NotifyEventsPlatform (/usr/local/lib/node_modules/homebridge-notifyevents/src/index.js:28:25)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:442:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:161:29)
[5/24/2022, 10:40:11 AM] Got SIGTERM, shutting down Homebridge...

**Comment by papajojo** [comment]
D'oh! Quick fixes are not always successful, sorry. Please try new version now, should work @nebosphere19 :)

**Comment by nebosphere19** [comment]
Thanks for the fast reply! It loads now, and creates the accessory but when I try to activate I get this:

5/24/2022, 7:22:45 PM] [NotifyEvents] [Fridge Door Notifier] Send message
[5/24/2022, 7:22:45 PM] [homebridge-notifyevents] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside write handler for characteristic: Invalid URL. See https://homebridge.io/w/JtMGR for more info.

**Comment by nebosphere19** [comment]
Debug mode yields this:

[5/24/2022, 7:31:24 PM] [NotifyEvents] [Fridge Door Notifier] Send message
[5/24/2022, 7:31:24 PM] [homebridge-notifyevents] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside write handler for characteristic: Invalid URL. See https://homebridge.io/w/JtMGR for more info.
[5/24/2022, 7:31:24 PM] [homebridge-notifyevents] TypeError: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at NotifyEventsMessage.sendMessage (/usr/local/lib/node_modules/homebridge-notifyevents/src/index.js:262:22)
    at NotifyEventsMessage.setOnHandler (/usr/local/lib/node_modules/homebridge-notifyevents/src/index.js:295:18)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1676:42)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)

**Comment by papajojo** [comment]
Hello, @nebosphere19. We are currently preparing a new release to fix your case and a couple of minor issues. Could you please send your homebridge version and plugin configuration json to support@notify.events so we could inspect and test it?

**Comment by nebosphere19** [comment]
Sent!

**Comment by nebosphere19** [comment]
I updated to V1.2.3 today and now I get no errors in homebridge. Yay! But still no SMS message when I activate the accessory. Boo...

**Comment by papajojo** [comment]
Good, that means that Homebridge plugin is working now. 

As for the SMS messages, please pay attention that there are couple of extra chargable notification methods on the side of the Notify.Events service (SMS is one of them). You can find more information [here](https://notify.events/wiki/your-account/billing/how-we-bill#extra-pay).

Please take a look at the dashboard of your Notify.Events channel and you will see that notifications are being received but cannot be sent via SMS due to insufficient funds. You might top up your balance to use SNS notifications or you can choose any other notification method that does not have additional fees.

Thanks again for the feedback!

**Comment by nebosphere19** [comment]
Ok - got it! So it's working for email integration now. I've tried the iOS app as well, but can't seem to get push notifications to work there, even though setup is pretty simple and I'm sure I've done everything correctly.

**Comment by papajojo** [comment]
Hello @nebosphere19. Sorry for the long reply, we missed your comment :( Is the problem still actual? 
We can see in our logs that iOS notifications are seems to be working now.

**Comment by nebosphere19** [comment]
Nope - looks good now. I didn’t realize you had to pay for SMS. I changed over to email. You can close this!
